### ISSUE TITLE
Now OK but

### ISSUE THREAD

**Issue by limelect** [havrlisan/zx-skiacomponents#3]
Now it is OK I had to restart my IDE
However, using variables from D12 does not help
So good luck again

**Comment by havrlisan** [comment]
I'm not sure what you're trying to tell me here. If I understand correctly, you're using Delphi 10.2, which this library does not yet support (it is clearly stated at the beginning of the readme). You're also trying to open the package that is for Delphi 12, which is why it doesn't work for your Delphi version.

Please be descriptive when making an issue, and don't create new ones if the issue is the same as an already existing one; you can comment on that one instead. I'll soon add a template that contains fields for the necessary information.

**Comment by havrlisan** [comment]
I've added some basic templates for issue creation. Please recreate and describe your problem, thanks.
